#!/usr/bin/env node
// Renders the short /books/ summary from data/books.json.
//
// data/books.json is generated by alexmercedcom/scripts/build-network-booklists.mjs
// from the entity layer. Do not edit it by hand; rerun that script, then this one.
//
// This page is deliberately a summary: the flagship titles only, each linking to
// its canonical page on books.alexmerced.com with a separate "Buy on Amazon" link.
// The full catalog lives on books.alexmerced.com and is not repeated here.
//
//   node scripts/build-books.mjs          rewrite books/index.html in place
//   node scripts/build-books.mjs --check  exit 1 if the page is out of date
//
// Fills these marker pairs in books/index.html:
//   <!-- books:list:start --> ... <!-- books:list:end -->
//   <!-- books:schema:start --> ... <!-- books:schema:end -->
//   <!-- books:count:start --> ... <!-- books:count:end -->

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pagePath = join(root, 'books/index.html');
const check = process.argv.includes('--check');

const data = JSON.parse(readFileSync(join(root, 'data/books.json'), 'utf8'));
const flagships = data.books.filter((b) => b.flagship);

// Free digital editions Dremio distributes. Not part of the entity layer yet,
// so they are kept here, keyed by catalog slug.
const freeEditions = {
  'apache-iceberg-the-definitive-guide': 'https://hello.dremio.com/wp-apache-iceberg-the-definitive-guide-reg.html',
  'apache-polaris-the-definitive-guide': 'https://hello.dremio.com/wp-apache-polaris-guide-reg.html',
};

// Covers committed to this repo. Amazon's image host refuses hotlinks from many
// clients, so a local copy wins when one exists.
const localCovers = {
  'apache-iceberg-the-definitive-guide': '/assets/img/cover-apache-iceberg-tdg.jpg',
  'apache-polaris-the-definitive-guide': '/assets/img/cover-apache-polaris-tdg.jpg',
  'architecting-an-apache-iceberg-lakehouse': '/assets/img/cover-architecting-an-apache-iceberg-lakehouse.jpg',
};

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function card(b) {
  const free = freeEditions[b.slug]
    ? `\n              <a href="${esc(freeEditions[b.slug])}" rel="noopener">Free digital edition from Dremio</a>`
    : '';
  return `        <li class="bookspage__item">
          <a class="bookspage__cover" href="${esc(b.canonicalPage)}" tabindex="-1" aria-hidden="true">
            <img src="${esc(localCovers[b.slug] ?? b.cover)}" alt="" loading="lazy" decoding="async">
          </a>
          <div>
            <h2 class="bookspage__title"><a href="${esc(b.canonicalPage)}">${esc(b.title)}</a></h2>
            <p class="bookspage__publisher">${esc(b.publisher)}</p>
            <p class="bookspage__desc">${esc(b.description)}</p>
            <p class="bookspage__links">
              <a href="${esc(b.amazon)}" rel="noopener">Buy on Amazon</a>${free}
            </p>
          </div>
        </li>`;
}

const schema = {
  '@context': 'https://schema.org',
  '@type': 'ItemList',
  name: 'Highlighted books by Alex Merced',
  numberOfItems: flagships.length,
  itemListElement: flagships.map((b, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    name: b.title,
    url: b.canonicalPage,
  })),
};

const blocks = {
  list: flagships.map(card).join('\n'),
  schema: `<script type="application/ld+json">${JSON.stringify(schema)}</script>`,
  count: String(data.totalInCatalog ?? data.count),
};

const html = readFileSync(pagePath, 'utf8');
let next = html;
for (const [name, body] of Object.entries(blocks)) {
  const re = new RegExp(`(<!-- books:${name}:start -->)[\\s\\S]*?(<!-- books:${name}:end -->)`);
  if (!re.test(next)) throw new Error(`books/index.html is missing books:${name} markers`);
  next = next.replace(re, (_m, a, z) => (name === 'count' ? `${a}${body}${z}` : `${a}\n${body}\n${z}`));
}

if (next === html) process.exit(0);
if (check) {
  console.error('books/index.html is out of date. Run: node scripts/build-books.mjs');
  process.exit(1);
}
writeFileSync(pagePath, next);
console.log('updated: books/index.html');
